Fix #762: Add a column for OTP attempt count
wultra/enrollment-server pull request #772
Opened 2023-05-30 12:48 UTC by jandusil

* Update table es_onboarding_otp -> new col 'total_attempts'
* Update 'total_attempts' count during various processes

2023-05-31 05:10 UTC, banterCZ requested changes
A good job. Just details to improve.

2023-05-31 05:10 UTC, banterCZ commented on docs/onboarding/Database-Structure.md
> +|--------------------------|---|---|--------------------------------------------------------------------------------------------------------------------------------------------------|
If reformatted, I would expect everything. Or nothing at all.

2023-05-31 05:10 UTC, banterCZ commented on docs/sql/oracle/onboarding/create-schema.sql
> +    TOTAL_ATTEMPTS INTEGER,
The default value should be reflected here as well.

2023-05-31 05:10 UTC, banterCZ commented on docs/sql/postgresql/onboarding/create-schema.sql
> +    total_attempts INTEGER,
dtto

2023-06-01 06:12 UTC, banterCZ commented on docs/sql/oracle/onboarding/create-schema.sql
> +    TOTAL_ATTEMPTS INTEGER DEFAULT 0,
Sorry, one more thing. It should also be mentioned in `PowerAuth-Enrollment-Onboarding-Server-1.5.0.md`. I know, it is a little duplicity with Liquibase, but the update process is not fine-tuned yet.

2023-06-08 11:01 UTC, banterCZ commented on docs/onboarding/Database-Structure.md
> +                          name VARCHAR(64) NOT NULL PRIMARY KEY,
Is this reformat needed?

2023-06-08 11:02 UTC, banterCZ commented on docs/onboarding/Database-Structure.md
> +| `id`                     | `VARCHAR(36)` | `NOT NULL PRIMARY KEY` | Autogenerated record identifier (UUID).
My idea was to reformat all columns of this single table or do not reformat it at all.

2023-06-08 11:37 UTC, banterCZ approved these changes
Good job.

2023-06-09 08:53 UTC, romanstrobl approved these changes
Looks good.

2023-06-12 09:58 UTC, merged